### ISSUE TITLE
Error in concurrent.futures happening on 

### ISSUE THREAD

**Issue by benjaoming** [learningequality/iceqube#31]
Happening when building on non-py 2.7

![image](https://user-images.githubusercontent.com/374612/34182304-fad28c76-e515-11e7-8910-6bdbc488c7f2.png)

```
Done in 25.17s.
INFO     Running Kolibri with the following settings: kolibri.deployment.default.settings.test
Traceback (most recent call last):
  File "/opt/python/3.4.6/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/python/3.4.6/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/travis/build/learningequality/kolibri/kolibri/__main__.py", line 8, in <module>
    main(args=sys.argv[1:])
  File "/home/travis/build/learningequality/kolibri/kolibri/utils/cli.py", line 578, in main
    manage(command, args=django_args)
  File "/home/travis/build/learningequality/kolibri/kolibri/utils/cli.py", line 409, in manage
    execute_from_command_line(argv=argv)
  File "/home/travis/build/learningequality/kolibri/kolibri/dist/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/travis/build/learningequality/kolibri/kolibri/dist/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/travis/build/learningequality/kolibri/kolibri/dist/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/travis/build/learningequality/kolibri/kolibri/dist/django/core/management/base.py", line 327, in execute
    self.check()
  File "/home/travis/build/learningequality/kolibri/kolibri/dist/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/travis/build/learningequality/kolibri/kolibri/dist/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/travis/build/learningequality/kolibri/kolibri/dist/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/travis/build/learningequality/kolibri/kolibri/dist/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/home/travis/build/learningequality/kolibri/kolibri/dist/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/home/travis/build/learningequality/kolibri/kolibri/dist/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/home/travis/build/learningequality/kolibri/kolibri/dist/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/travis/build/learningequality/kolibri/kolibri/dist/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/travis/build/learningequality/kolibri/kolibri/dist/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/travis/build/learningequality/kolibri/kolibri/dist/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/travis/build/learningequality/kolibri/.tox/pythonbuild3.4/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/travis/build/learningequality/kolibri/kolibri/deployment/default/urls.py", line 37, in <module>
    url(r'^api/', include('kolibri.tasks.api_urls')),
  File "/home/travis/build/learningequality/kolibri/kolibri/dist/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/travis/build/learningequality/kolibri/.tox/pythonbuild3.4/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/travis/build/learningequality/kolibri/kolibri/tasks/api_urls.py", line 3, in <module>
    from .api import TasksViewSet
  File "/home/travis/build/learningequality/kolibri/kolibri/tasks/api.py", line 8, in <module>
    from iceqube.exceptions import UserCancelledError
  File "/home/travis/build/learningequality/kolibri/kolibri/dist/iceqube/exceptions.py", line 1, in <module>
    from concurrent.futures import CancelledError
  File "/home/travis/build/learningequality/kolibri/kolibri/dist/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/home/travis/build/learningequality/kolibri/kolibri/dist/concurrent/futures/_base.py", line 381
    raise exception_type, self._exception, self._traceback
                        ^
SyntaxError: invalid syntax
child_process.js:516
    throw err;
    ^
Error: Command failed: python -m kolibri manage webpack_json -- --outputfile /tmp/1171119-7524-1g6hkbe.twc8ilik9.json
INFO     Running Kolibri with the following settings: kolibri.deployment.default.settings.test
Traceback (most recent call last):
  File "/opt/python/3.4.6/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/python/3.4.6/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/travis/build/learningequality/kolibri/kolibri/__main__.py", line 8, in <module>
    main(args=sys.argv[1:])
  File "/home/travis/build/learningequality/kolibri/kolibri/utils/cli.py", line 578, in main
    manage(command, args=django_args)
  File "/home/travis/build/learningequality/kolibri/kolibri/utils/cli.py", line 409, in manage
    execute_from_command_line(argv=argv)
  File "/home/travis/build/learningequality/kolibri/kolibri/dist/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/travis/build/learningequality/kolibri/kolibri/dist/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/travis/build/learningequality/kolibri/kolibri/dist/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/travis/build/learningequality/kolibri/kolibri/dist/django/core/management/base.py", line 327, in execute
    self.check()
  File "/home/travis/build/learningequality/kolibri/kolibri/dist/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/travis/build/learningequality/kolibri/kolibri/dist/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/travis/build/learningequality/kolibri/kolibri/dist/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/travis/build/learningequality/kolibri/kolibri/dist/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/home/travis/build/learningequality/kolibri/kolibri/dist/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/home/travis/build/learningequality/kolibri/kolibri/dist/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/home/travis/build/learningequality/kolibri/kolibri/dist/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/travis/build/learningequality/kolibri/kolibri/dist/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/travis/build/learningequality/kolibri/kolibri/dist/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/travis/build/learningequality/kolibri/kolibri/dist/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/travis/build/learningequality/kolibri/.tox/pythonbuild3.4/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/travis/build/learningequality/kolibri/kolibri/deployment/default/urls.py", line 37, in <module>
    url(r'^api/', include('kolibri.tasks.api_urls')),
  File "/home/travis/build/learningequality/kolibri/kolibri/dist/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/travis/build/learningequality/kolibri/.tox/pythonbuild3.4/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/travis/build/learningequality/kolibri/kolibri/tasks/api_urls.py", line 3, in <module>
    from .api import TasksViewSet
  File "/home/travis/build/learningequality/kolibri/kolibri/tasks/api.py", line 8, in <module>
    from iceqube.exceptions import UserCancelledError
  File "/home/travis/build/learningequality/kolibri/kolibri/dist/iceqube/exceptions.py", line 1, in <module>
    from concurrent.futures import CancelledError
  File "/home/travis/build/learningequality/kolibri/kolibri/dist/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/home/travis/build/learningequality/kolibri/kolibri/dist/concurrent/futures/_base.py", line 381
    raise exception_type, self._exception, self._traceback
                        ^
SyntaxError: invalid syntax
    at checkExecSyncError (child_process.js:473:13)
    at execSync (child_process.js:513:13)
    at module.exports (/home/travis/build/learningequality/kolibri/frontend_build/src/read_webpack_json.js:10:3)
    at Object.<anonymous> (/home/travis/build/learningequality/kolibri/frontend_build/src/install_dependencies.js:6:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
error Command failed with exit code 1.
make: *** [assets] Error 1
Traceback (last called is first):
     source() in conditional/test_build.sh:17
     main() in /home/travis/build/learningequality/kolibri/test/if.sh:124
The command make dist > /dev/null exited with exit code 2.
ERROR: InvocationError: '/home/travis/build/learningequality/kolibri/test/if.sh setup_changed'
___________________________________ summary ____________________________________
ERROR:   pythonbuild3.4: commands failed
```

**Comment by benjaoming** [comment]
I get it now: `futures` is only supposed to be loaded in Python 2, and this will happen if you load it in Python 3.

See: https://github.com/agronholm/pythonfutures/issues/41
